apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-process-deployment
  namespace: process-stack
  labels:
    app: go-process
spec:
  replicas: 5
  selector:
    matchLabels:
      app: go-process
  template:
    metadata:
      labels:
        app: go-process
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: go-process
        image: 657026912035.dkr.ecr.eu-west-1.amazonaws.com/dc-container-repo:go-process-latest
        ports:
        - containerPort: 1234 # change this to the port of go-process dockerfile expose