apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: frontend
        image: 657026912035.dkr.ecr.eu-west-1.amazonaws.com/dc-container-repo:frontend-latest
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          value: "https://api.norbertknez.me"