apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: webapp
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      imagePullPolicy: Always
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "200m"
      containers:
      - name: backend
        image: 657026912035.dkr.ecr.eu-west-1.amazonaws.com/dc-container-repo:backend-latest
        ports:
        - containerPort: 8080
        env:
        - name: FRONTEND_BASE_URL
          value: "https://norbertknez.me"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_NAME  
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_SECRET
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_PROFILE
          value: "prod"
        - name: PROCESSING_API_BASE_URL
          value: "http://go-api-service:1234"
        - name: PROCESSING_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: go-api-secret
              key: GO_API_TOKEN