name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Change to the correct directory
      run: cd DCS4-Backend
    - name: Install dependencies
      run: npm install
      working-directory: ./DCS4-Backend
    - name: Run tests
      run: npm test
      working-directory: ./DCS4-Backend
