apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"backend"},"name":"backend-deployment","namespace":"webapp"},"spec":{"replic>
  creationTimestamp: "2025-06-09T17:26:57Z"
  generation: 1
  labels:
    app: backend
  name: backend-deployment
  namespace: webapp
  resourceVersion: "125232"
  uid: 6e8ac48d-1f81-4d92-b6d1-fbec582333cf
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - env:
        - name: FRONTEND_BASE_URL
          value: https://norbertknez.me
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: DB_HOST
              name: db-secret
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: DB_PORT
              name: db-secret
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: DB_NAME
              name: db-secret
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: DB_USER
              name: db-secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: db-secret
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: JWT_SECRET
              name: jwt-secret
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_PROFILE
          value: prod
        - name: PROCESSING_API_BASE_URL
          value: http://go-api-service:1234
        - name: PROCESSING_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: GO_API_TOKEN
              name: go-api-secret
        image: 657026912035.dkr.ecr.eu-west-1.amazonaws.com/dc-container-repo:backend-latest
        imagePullPolicy: Always
        name: backend
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: "300Mi"
            cpu: "50m"
          limits:
            memory: "500Mi"
            cpu: "200m"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ecr-registry-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 5
  conditions:
  - lastTransitionTime: "2025-06-09T17:27:05Z"
    lastUpdateTime: "2025-06-09T17:27:05Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-06-09T17:26:57Z"
    lastUpdateTime: "2025-06-09T17:27:06Z"
    message: ReplicaSet "backend-deployment-65b9b5f87f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 5
  replicas: 5
  updatedReplicas: 5
